-- Criação da tabela de Bairros para sincronização
CREATE TABLE AS_BAIRROS (
    ID_SISTEMA NUMBER NOT NULL,
    CODBAI NUMBER NOT NULL,
    CODREG NUMBER,
    DESCRICAOCORREIO VARCHAR2(255),
    DTALTER TIMESTAMP,
    NOMEBAI VARCHAR2(255),
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S',
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AS_BAIRROS PRIMARY KEY (ID_SISTEMA, CODBAI)
);

-- Índices para melhorar performance
CREATE INDEX IDX_AS_BAIRROS_SIST ON AS_BAIRROS(ID_SISTEMA);
CREATE INDEX IDX_AS_BAIRROS_ATUAL ON AS_BAIRROS(SANKHYA_ATUAL);

COMMENT ON TABLE AS_BAIRROS IS 'Tabela de sincronização de Bairros do Sankhya';
COMMENT ON COLUMN AS_BAIRROS.ID_SISTEMA IS 'ID do sistema/empresa no contrato';
COMMENT ON COLUMN AS_BAIRROS.CODBAI IS 'Código do Bairro no Sankhya';
COMMENT ON COLUMN AS_BAIRROS.CODREG IS 'Código da Região';
COMMENT ON COLUMN AS_BAIRROS.DESCRICAOCORREIO IS 'Descrição correios';
COMMENT ON COLUMN AS_BAIRROS.DTALTER IS 'Data de alteração';
COMMENT ON COLUMN AS_BAIRROS.NOMEBAI IS 'Nome do Bairro';
COMMENT ON COLUMN AS_BAIRROS.SANKHYA_ATUAL IS 'Flag se o registro ainda existe no Sankhya (S) ou foi removido (N)';
COMMENT ON COLUMN AS_BAIRROS.DT_ULT_CARGA IS 'Data da última atualização/carga';
