
-- Script para criar a tabela AS_PRODUTOS no Oracle
-- Tabela responsável por armazenar os produtos sincronizados de cada empresa

-- Criar a tabela AS_PRODUTOS
CREATE TABLE AS_PRODUTOS (
    ID_SISTEMA NUMBER NOT NULL,
    CODPROD NUMBER NOT NULL,
    DESCRPROD VARCHAR2(200),
    ATIVO CHAR(1),
    LOCAL VARCHAR2(100),
    MARCA VARCHAR2(100),
    CARACTERISTICAS VARCHAR2(500),
    UNIDADE VARCHAR2(10),
    VLRCOMERC NUMBER(15,2),
    ESTOQUE NUMBER(15,3),
    REFERENCIA VARCHAR2(50),
    CODVOL VARCHAR2(10),
    CODEANBARRA VARCHAR2(50),
    DESCRCOMPLETA VARCHAR2(4000),
    CODGRUPOPROD NUMBER,
    CODMARCA NUMBER,
    COMPRADOR VARCHAR2(60),
    PESO NUMBER(15,3),
    PESOLIQ NUMBER(15,3),
    ALTURA NUMBER(15,3),
    LARGURA NUMBER(15,3),
    COMPRIMENTO NUMBER(15,3),
    NCMSH VARCHAR2(20),
    ORIGPROD CHAR(1),
    CONTROLE CHAR(1),
    USOPROD CHAR(1),
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S' CHECK (SANKHYA_ATUAL IN ('S', 'N')),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_as_produtos PRIMARY KEY (ID_SISTEMA, CODPROD),
    CONSTRAINT fk_as_produtos_empresa FOREIGN KEY (ID_SISTEMA) REFERENCES AD_CONTRATOS(ID_EMPRESA) ON DELETE CASCADE
);

-- Criar índices para melhorar performance
CREATE INDEX idx_as_produtos_sistema ON AS_PRODUTOS(ID_SISTEMA);
CREATE INDEX idx_as_produtos_atual ON AS_PRODUTOS(SANKHYA_ATUAL);
CREATE INDEX idx_as_produtos_descr ON AS_PRODUTOS(DESCRPROD);
CREATE INDEX idx_as_produtos_referencia ON AS_PRODUTOS(REFERENCIA);
CREATE INDEX idx_as_produtos_ativo ON AS_PRODUTOS(ATIVO);
CREATE INDEX idx_as_produtos_grupo ON AS_PRODUTOS(CODGRUPOPROD);
CREATE INDEX idx_as_produtos_marca ON AS_PRODUTOS(CODMARCA);
CREATE INDEX idx_as_produtos_carga ON AS_PRODUTOS(DT_ULT_CARGA);
CREATE INDEX idx_as_produtos_ean ON AS_PRODUTOS(CODEANBARRA);

-- Criar trigger para atualizar DT_ULT_CARGA automaticamente
CREATE OR REPLACE TRIGGER trg_produtos_atualizacao
BEFORE UPDATE ON AS_PRODUTOS
FOR EACH ROW
BEGIN
    :NEW.DT_ULT_CARGA := CURRENT_TIMESTAMP;
END;
/

-- Comentários nas colunas
COMMENT ON TABLE AS_PRODUTOS IS 'Tabela de sincronização de produtos do Sankhya por empresa';
COMMENT ON COLUMN AS_PRODUTOS.ID_SISTEMA IS 'Identificador da empresa (segregador multi-tenant)';
COMMENT ON COLUMN AS_PRODUTOS.CODPROD IS 'Código do produto no Sankhya';
COMMENT ON COLUMN AS_PRODUTOS.DESCRPROD IS 'Descrição do produto';
COMMENT ON COLUMN AS_PRODUTOS.ATIVO IS 'Status ativo/inativo';
COMMENT ON COLUMN AS_PRODUTOS.LOCAL IS 'Local de armazenamento';
COMMENT ON COLUMN AS_PRODUTOS.MARCA IS 'Marca do produto';
COMMENT ON COLUMN AS_PRODUTOS.CARACTERISTICAS IS 'Características do produto';
COMMENT ON COLUMN AS_PRODUTOS.UNIDADE IS 'Unidade de medida';
COMMENT ON COLUMN AS_PRODUTOS.VLRCOMERC IS 'Valor comercial';
COMMENT ON COLUMN AS_PRODUTOS.ESTOQUE IS 'Quantidade em estoque';
COMMENT ON COLUMN AS_PRODUTOS.REFERENCIA IS 'Referência do produto';
COMMENT ON COLUMN AS_PRODUTOS.CODVOL IS 'Código do volume';
COMMENT ON COLUMN AS_PRODUTOS.CODEANBARRA IS 'Código de barras EAN';
COMMENT ON COLUMN AS_PRODUTOS.DESCRCOMPLETA IS 'Descrição completa do produto';
COMMENT ON COLUMN AS_PRODUTOS.CODGRUPOPROD IS 'Código do grupo de produto';
COMMENT ON COLUMN AS_PRODUTOS.CODMARCA IS 'Código da marca no Sankhya';
COMMENT ON COLUMN AS_PRODUTOS.COMPRADOR IS 'Comprador responsável';
COMMENT ON COLUMN AS_PRODUTOS.PESO IS 'Peso bruto';
COMMENT ON COLUMN AS_PRODUTOS.PESOLIQ IS 'Peso líquido';
COMMENT ON COLUMN AS_PRODUTOS.ALTURA IS 'Altura do produto';
COMMENT ON COLUMN AS_PRODUTOS.LARGURA IS 'Largura do produto';
COMMENT ON COLUMN AS_PRODUTOS.COMPRIMENTO IS 'Comprimento do produto';
COMMENT ON COLUMN AS_PRODUTOS.NCMSH IS 'Código NCM';
COMMENT ON COLUMN AS_PRODUTOS.ORIGPROD IS 'Origem do produto';
COMMENT ON COLUMN AS_PRODUTOS.CONTROLE IS 'Tipo de controle (L=Lote, E=Estoque)';
COMMENT ON COLUMN AS_PRODUTOS.USOPROD IS 'Uso do produto (R=Revenda, C=Consumo, I=Imobilizado)';
COMMENT ON COLUMN AS_PRODUTOS.SANKHYA_ATUAL IS 'Indica se o registro está ativo no Sankhya (S=Sim, N=Soft Delete)';
COMMENT ON COLUMN AS_PRODUTOS.DT_ULT_CARGA IS 'Data da última sincronização deste registro';
COMMENT ON COLUMN AS_PRODUTOS.DT_CRIACAO IS 'Data de criação do registro na tabela';

-- Criar view para consultar apenas produtos ativos
CREATE OR REPLACE VIEW VW_PRODUTOS_ATIVOS AS
SELECT 
    p.ID_SISTEMA,
    p.CODPROD,
    p.DESCRPROD,
    p.ATIVO,
    p.LOCAL,
    p.MARCA,
    p.CARACTERISTICAS,
    p.UNIDADE,
    p.VLRCOMERC,
    p.ESTOQUE,
    p.REFERENCIA,
    p.CODVOL,
    p.CODEANBARRA,
    p.DESCRCOMPLETA,
    p.CODGRUPOPROD,
    p.CODMARCA,
    p.COMPRADOR,
    p.PESO,
    p.PESOLIQ,
    p.ALTURA,
    p.LARGURA,
    p.COMPRIMENTO,
    p.NCMSH,
    p.ORIGPROD,
    p.CONTROLE,
    p.USOPROD,
    p.SANKHYA_ATUAL,
    p.DT_ULT_CARGA,
    p.DT_CRIACAO,
    p.IMAGEM_CONTENT_TYPE,
    p.IMAGEM_ATUALIZADA_EM,
    CASE WHEN p.IMAGEM IS NOT NULL THEN 'S' ELSE 'N' END AS TEM_IMAGEM,
    c.EMPRESA,
    c.CNPJ
FROM AS_PRODUTOS p
INNER JOIN AD_CONTRATOS c ON p.ID_SISTEMA = c.ID_EMPRESA
WHERE p.SANKHYA_ATUAL = 'S'
  AND c.ATIVO = 'S';

COMMENT ON VIEW VW_PRODUTOS_ATIVOS IS 'View de produtos ativos sincronizados';

COMMIT;
