-- Criação da tabela de Grupos de Produtos para sincronização
CREATE TABLE AS_GRUPOS_PRODUTOS (
    ID_SISTEMA NUMBER NOT NULL,
    CODGRUPOPROD NUMBER NOT NULL,
    DESCRGRUPOPROD VARCHAR2(255),
    DHALTER TIMESTAMP,
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S',
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AS_GRUPOS_PRODUTOS PRIMARY KEY (ID_SISTEMA, CODGRUPOPROD)
);

-- Índices para melhorar performance
CREATE INDEX IDX_AS_GRUPOS_PRODUTOS_SIST ON AS_GRUPOS_PRODUTOS(ID_SISTEMA);
CREATE INDEX IDX_AS_GRUPOS_PRODUTOS_ATUAL ON AS_GRUPOS_PRODUTOS(SANKHYA_ATUAL);

COMMENT ON TABLE AS_GRUPOS_PRODUTOS IS 'Tabela de sincronização de Grupos de Produtos do Sankhya';
COMMENT ON COLUMN AS_GRUPOS_PRODUTOS.ID_SISTEMA IS 'ID do sistema/empresa no contrato';
COMMENT ON COLUMN AS_GRUPOS_PRODUTOS.CODGRUPOPROD IS 'Código do Grupo de Produto no Sankhya';
COMMENT ON COLUMN AS_GRUPOS_PRODUTOS.DESCRGRUPOPROD IS 'Descrição do Grupo de Produto';
COMMENT ON COLUMN AS_GRUPOS_PRODUTOS.SANKHYA_ATUAL IS 'Flag se o registro ainda existe no Sankhya (S) ou foi removido (N)';
COMMENT ON COLUMN AS_GRUPOS_PRODUTOS.DT_ULT_CARGA IS 'Data da última atualização/carga';
