-- Criação da tabela de Estados (UF) para sincronização
CREATE TABLE AS_ESTADOS (
    ID_SISTEMA NUMBER NOT NULL,
    CODUF NUMBER NOT NULL,
    UF VARCHAR2(2),
    DESCRICAO VARCHAR2(255),
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S',
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AS_ESTADOS PRIMARY KEY (ID_SISTEMA, CODUF)
);

-- Índices
CREATE INDEX IDX_AS_ESTADOS_SIST ON AS_ESTADOS(ID_SISTEMA);
CREATE INDEX IDX_AS_ESTADOS_ATUAL ON AS_ESTADOS(SANKHYA_ATUAL);

COMMENT ON TABLE AS_ESTADOS IS 'Tabela de sincronização de Estados (UF) do Sankhya';
COMMENT ON COLUMN AS_ESTADOS.ID_SISTEMA IS 'ID do sistema/empresa no contrato';
COMMENT ON COLUMN AS_ESTADOS.CODUF IS 'Código da UF no Sankhya';
COMMENT ON COLUMN AS_ESTADOS.UF IS 'Sigla da UF';
COMMENT ON COLUMN AS_ESTADOS.DESCRICAO IS 'Nome/Descrição do Estado';
COMMENT ON COLUMN AS_ESTADOS.SANKHYA_ATUAL IS 'Flag se o registro ainda existe no Sankhya (S) ou foi removido (N)';
COMMENT ON COLUMN AS_ESTADOS.DT_ULT_CARGA IS 'Data da última atualização/carga';
