-- Criação da tabela de Cidades para sincronização
CREATE TABLE AS_CIDADES (
    ID_SISTEMA NUMBER NOT NULL,
    CODCID NUMBER NOT NULL,
    UFNOMECID VARCHAR2(255),
    UF NUMBER,
    CODREG NUMBER,
    DESCRICAOCORREIO VARCHAR2(255),
    NOMECID VARCHAR2(255),
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S',
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AS_CIDADES PRIMARY KEY (ID_SISTEMA, CODCID)
);

-- Índices para melhorar performance
CREATE INDEX IDX_AS_CIDADES_SIST ON AS_CIDADES(ID_SISTEMA);
CREATE INDEX IDX_AS_CIDADES_ATUAL ON AS_CIDADES(SANKHYA_ATUAL);

COMMENT ON TABLE AS_CIDADES IS 'Tabela de sincronização de Cidades do Sankhya';
COMMENT ON COLUMN AS_CIDADES.ID_SISTEMA IS 'ID do sistema/empresa no contrato';
COMMENT ON COLUMN AS_CIDADES.CODCID IS 'Código da Cidade no Sankhya';
COMMENT ON COLUMN AS_CIDADES.UFNOMECID IS 'UF - Nome da Cidade';
COMMENT ON COLUMN AS_CIDADES.UF IS 'Código da Unidade Federativa (UF)';
COMMENT ON COLUMN AS_CIDADES.CODREG IS 'Código da Região';
COMMENT ON COLUMN AS_CIDADES.DESCRICAOCORREIO IS 'Descrição correios';
COMMENT ON COLUMN AS_CIDADES.NOMECID IS 'Nome da Cidade';
COMMENT ON COLUMN AS_CIDADES.SANKHYA_ATUAL IS 'Flag se o registro ainda existe no Sankhya (S) ou foi removido (N)';
COMMENT ON COLUMN AS_CIDADES.DT_ULT_CARGA IS 'Data da última atualização/carga';
