-- Criação da tabela de Regiões para sincronização
CREATE TABLE AS_REGIOES (
    ID_SISTEMA NUMBER NOT NULL,
    CODREG NUMBER NOT NULL,
    NOMEREG VARCHAR2(255),
    ATIVA CHAR(1),
    ANALITICA CHAR(1),
    CODTAB NUMBER,
    CODTABMIN NUMBER,
    FRETEMIN NUMBER(19,4),
    PERCCUSVAR NUMBER(19,4),
    PERCDESCFOB NUMBER(19,4),
    CODVEND NUMBER,
    PERCADICIONAL NUMBER(19,4),
    PERCPREMIO NUMBER(19,4),
    GERARRECEITA CHAR(1),
    VLRANTECIPACAO NUMBER(19,4),
    GRAU NUMBER,
    CODREGPAI NUMBER,
    VENDAMIN NUMBER(19,4),
    DTALTER TIMESTAMP,
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S',
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AS_REGIOES PRIMARY KEY (ID_SISTEMA, CODREG)
);

-- Índices para melhorar performance
CREATE INDEX IDX_AS_REGIOES_SIST ON AS_REGIOES(ID_SISTEMA);
CREATE INDEX IDX_AS_REGIOES_ATUAL ON AS_REGIOES(SANKHYA_ATUAL);

COMMENT ON TABLE AS_REGIOES IS 'Tabela de sincronização de Regiões do Sankhya';
COMMENT ON COLUMN AS_REGIOES.ID_SISTEMA IS 'ID do sistema/empresa no contrato';
COMMENT ON COLUMN AS_REGIOES.CODREG IS 'Código da Região no Sankhya';
COMMENT ON COLUMN AS_REGIOES.NOMEREG IS 'Nome da Região';
COMMENT ON COLUMN AS_REGIOES.ATIVA IS 'Ativa (S/N)';
COMMENT ON COLUMN AS_REGIOES.ANALITICA IS 'Analítica (S/N)';
COMMENT ON COLUMN AS_REGIOES.CODTAB IS 'Tabela de Preço';
COMMENT ON COLUMN AS_REGIOES.CODTABMIN IS 'Tabela de Preço Mínimo';
COMMENT ON COLUMN AS_REGIOES.FRETEMIN IS 'Frete Mínimo';
COMMENT ON COLUMN AS_REGIOES.PERCCUSVAR IS '% Custo Variável';
COMMENT ON COLUMN AS_REGIOES.PERCDESCFOB IS '% Desc. FOB';
COMMENT ON COLUMN AS_REGIOES.CODVEND IS 'Vendedor';
COMMENT ON COLUMN AS_REGIOES.PERCADICIONAL IS 'Perc. Adicional';
COMMENT ON COLUMN AS_REGIOES.PERCPREMIO IS 'Perc. Prêmio';
COMMENT ON COLUMN AS_REGIOES.GERARRECEITA IS 'Gerar Receita';
COMMENT ON COLUMN AS_REGIOES.VLRANTECIPACAO IS 'Valor Antecipação';
COMMENT ON COLUMN AS_REGIOES.GRAU IS 'Grau';
COMMENT ON COLUMN AS_REGIOES.CODREGPAI IS 'Código da Região Pai';
COMMENT ON COLUMN AS_REGIOES.VENDAMIN IS 'Venda Mínima';
COMMENT ON COLUMN AS_REGIOES.SANKHYA_ATUAL IS 'Flag se o registro ainda existe no Sankhya (S) ou foi removido (N)';
COMMENT ON COLUMN AS_REGIOES.DT_ULT_CARGA IS 'Data da última atualização/carga';
