
-- Tabela de logs de sincronização
CREATE TABLE AS_SYNC_LOGS (
    ID_LOG              NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SISTEMA          NUMBER(10)      NOT NULL,
    EMPRESA             VARCHAR2(100)   NOT NULL,
    TABELA              VARCHAR2(50)    NOT NULL,
    STATUS              VARCHAR2(20)    NOT NULL CHECK (STATUS IN ('SUCESSO', 'FALHA')),
    TOTAL_REGISTROS     NUMBER(10)      DEFAULT 0,
    REGISTROS_INSERIDOS NUMBER(10)      DEFAULT 0,
    REGISTROS_ATUALIZADOS NUMBER(10)    DEFAULT 0,
    REGISTROS_DELETADOS NUMBER(10)      DEFAULT 0,
    DURACAO_MS          NUMBER(10),
    MENSAGEM_ERRO       VARCHAR2(4000),
    DATA_INICIO         TIMESTAMP       NOT NULL,
    DATA_FIM            TIMESTAMP,
    DATA_CRIACAO        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SYNC_LOGS_EMPRESA FOREIGN KEY (ID_SISTEMA) REFERENCES AD_CONTRATOS(ID_EMPRESA)
);

-- Índices para melhorar performance de consultas
CREATE INDEX IDX_SYNC_LOGS_SISTEMA ON AS_SYNC_LOGS(ID_SISTEMA);
CREATE INDEX IDX_SYNC_LOGS_TABELA ON AS_SYNC_LOGS(TABELA);
CREATE INDEX IDX_SYNC_LOGS_STATUS ON AS_SYNC_LOGS(STATUS);
CREATE INDEX IDX_SYNC_LOGS_DATA ON AS_SYNC_LOGS(DATA_CRIACAO);
CREATE INDEX IDX_SYNC_LOGS_EMPRESA ON AS_SYNC_LOGS(EMPRESA);

-- Comentários nas colunas
COMMENT ON TABLE AS_SYNC_LOGS IS 'Logs de sincronização de dados entre Sankhya e sistema local';
COMMENT ON COLUMN AS_SYNC_LOGS.ID_LOG IS 'Identificador único do log';
COMMENT ON COLUMN AS_SYNC_LOGS.ID_SISTEMA IS 'ID da empresa/contrato';
COMMENT ON COLUMN AS_SYNC_LOGS.EMPRESA IS 'Nome da empresa';
COMMENT ON COLUMN AS_SYNC_LOGS.TABELA IS 'Nome da tabela sincronizada';
COMMENT ON COLUMN AS_SYNC_LOGS.STATUS IS 'Status da sincronização (SUCESSO ou FALHA)';
COMMENT ON COLUMN AS_SYNC_LOGS.TOTAL_REGISTROS IS 'Total de registros processados';
COMMENT ON COLUMN AS_SYNC_LOGS.REGISTROS_INSERIDOS IS 'Quantidade de registros inseridos';
COMMENT ON COLUMN AS_SYNC_LOGS.REGISTROS_ATUALIZADOS IS 'Quantidade de registros atualizados';
COMMENT ON COLUMN AS_SYNC_LOGS.REGISTROS_DELETADOS IS 'Quantidade de registros deletados';
COMMENT ON COLUMN AS_SYNC_LOGS.DURACAO_MS IS 'Duração da sincronização em milissegundos';
COMMENT ON COLUMN AS_SYNC_LOGS.MENSAGEM_ERRO IS 'Mensagem de erro em caso de falha';
COMMENT ON COLUMN AS_SYNC_LOGS.DATA_INICIO IS 'Data/hora de início da sincronização';
COMMENT ON COLUMN AS_SYNC_LOGS.DATA_FIM IS 'Data/hora de fim da sincronização';
COMMENT ON COLUMN AS_SYNC_LOGS.DATA_CRIACAO IS 'Data/hora de criação do registro';
