-- Criação da tabela de Empresas para sincronização
CREATE TABLE AS_EMPRESAS (
    ID_SISTEMA NUMBER NOT NULL,
    CODEMP NUMBER NOT NULL,
    NOMEFANTASIA VARCHAR2(255),
    RAZAOSOCIAL VARCHAR2(255),
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S',
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AS_EMPRESAS PRIMARY KEY (ID_SISTEMA, CODEMP)
);

-- Índices para melhorar performance
CREATE INDEX IDX_AS_EMPRESAS_SIST ON AS_EMPRESAS(ID_SISTEMA);
CREATE INDEX IDX_AS_EMPRESAS_ATUAL ON AS_EMPRESAS(SANKHYA_ATUAL);

COMMENT ON TABLE AS_EMPRESAS IS 'Tabela de sincronização de Empresas do Sankhya';
COMMENT ON COLUMN AS_EMPRESAS.ID_SISTEMA IS 'ID do sistema/empresa no contrato';
COMMENT ON COLUMN AS_EMPRESAS.CODEMP IS 'Código da Empresa no Sankhya';
COMMENT ON COLUMN AS_EMPRESAS.NOMEFANTASIA IS 'Nome Fantasia';
COMMENT ON COLUMN AS_EMPRESAS.RAZAOSOCIAL IS 'Razão Social';
COMMENT ON COLUMN AS_EMPRESAS.SANKHYA_ATUAL IS 'Flag se o registro ainda existe no Sankhya (S) ou foi removido (N)';
COMMENT ON COLUMN AS_EMPRESAS.DT_ULT_CARGA IS 'Data da última atualização/carga';
