-- Script para criação da tabela AS_VOLUME_ALTERNATIVO no Oracle
-- Mapeamento da entidade ProdutoUnidade (TGFVOP) do Sankhya

CREATE TABLE AS_VOLUME_ALTERNATIVO (
    ID_SISTEMA NUMBER NOT NULL,
    CODPROD VARCHAR2(20) NOT NULL,
    CODVOL VARCHAR2(10) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S',
    CAMADAS NUMBER,
    CODBARRA VARCHAR2(50),
    CONTROLE VARCHAR2(10),
    DESCRDANFE VARCHAR2(200),
    DESCRUNTRIBEXPORT VARCHAR2(200),
    DIVIDEMULTIPLICA VARCHAR2(10),
    LASTRO NUMBER,
    M3 NUMBER,
    MULTIPVLR NUMBER,
    OPCAOSEP VARCHAR2(10),
    OPCOESGERAR0220 VARCHAR2(10),
    QTDDECIMAISUPF NUMBER,
    QUANTIDADE NUMBER,
    SELECIONADO VARCHAR2(10),
    TIPCODBARRA VARCHAR2(10),
    TIPGTINNFE NUMBER,
    UNDTRIBRECOB VARCHAR2(10),
    UNIDSELO VARCHAR2(10),
    UNIDTRIB VARCHAR2(10),
    UNTRIBEXPORTACAO VARCHAR2(10),
    SANKHYA_ATUAL CHAR(1) DEFAULT 'S' CHECK (SANKHYA_ATUAL IN ('S', 'N')),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_as_volume_alternativo PRIMARY KEY (ID_SISTEMA, CODPROD, CODVOL),
    CONSTRAINT fk_as_vol_alt_sistema FOREIGN KEY (ID_SISTEMA) REFERENCES AD_CONTRATOS(ID_EMPRESA) ON DELETE CASCADE
);

-- Índices para performance
CREATE INDEX idx_as_vol_alt_sistema ON AS_VOLUME_ALTERNATIVO(ID_SISTEMA);
CREATE INDEX idx_as_vol_alt_prod ON AS_VOLUME_ALTERNATIVO(CODPROD);
CREATE INDEX idx_as_vol_alt_atual ON AS_VOLUME_ALTERNATIVO(SANKHYA_ATUAL);

-- Comentários
COMMENT ON TABLE AS_VOLUME_ALTERNATIVO IS 'Tabela de volumes/unidades alternativas dos produtos do Sankhya';
COMMENT ON COLUMN AS_VOLUME_ALTERNATIVO.ID_SISTEMA IS 'ID da empresa/sistema';
COMMENT ON COLUMN AS_VOLUME_ALTERNATIVO.CODPROD IS 'Código do produto';
COMMENT ON COLUMN AS_VOLUME_ALTERNATIVO.CODVOL IS 'Código do volume/unidade';
COMMENT ON COLUMN AS_VOLUME_ALTERNATIVO.QUANTIDADE IS 'Fator de conversão';

COMMIT;
