
-- =====================================================
-- Script de Correção: Adicionar Colunas Faltantes
-- Alvos: AS_TIPOS_OPERACAO, AS_TIPOS_NEGOCIACAO, 
--        AS_REGIOES, AS_GRUPOS_PRODUTOS, AS_EXCECAO_PRECO,
--        AS_PARCEIROS
-- =====================================================

-- 1. AS_TIPOS_OPERACAO
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AS_TIPOS_OPERACAO ADD (DHALTER TIMESTAMP)';
   DBMS_OUTPUT.PUT_LINE('✅ Coluna DHALTER adicionada em AS_TIPOS_OPERACAO');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 2. AS_TIPOS_NEGOCIACAO
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AS_TIPOS_NEGOCIACAO ADD (DHALTER TIMESTAMP)';
   DBMS_OUTPUT.PUT_LINE('✅ Coluna DHALTER adicionada em AS_TIPOS_NEGOCIACAO');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 3. AS_REGIOES
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AS_REGIOES ADD (DTALTER TIMESTAMP)';
   DBMS_OUTPUT.PUT_LINE('✅ Coluna DTALTER adicionada em AS_REGIOES');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 4. AS_GRUPOS_PRODUTOS
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AS_GRUPOS_PRODUTOS ADD (DHALTER TIMESTAMP)';
   DBMS_OUTPUT.PUT_LINE('✅ Coluna DHALTER adicionada em AS_GRUPOS_PRODUTOS');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 5. AS_EXCECAO_PRECO
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AS_EXCECAO_PRECO ADD (DHALTREG TIMESTAMP)';
   DBMS_OUTPUT.PUT_LINE('✅ Coluna DHALTREG adicionada em AS_EXCECAO_PRECO');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 6. AS_PARCEIROS
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AS_PARCEIROS ADD (DTALTER TIMESTAMP)';
   DBMS_OUTPUT.PUT_LINE('✅ Coluna DTALTER adicionada em AS_PARCEIROS');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

COMMIT;
